apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-processor-31233
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/billing-processor-31233
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
